edition = "2023";

package aim;

message PlaylistDef {
  string description = 1;

  // Standard playlist with explicit items.
  repeated PlaylistItem items = 2;

  LevelsPlaylistDef levels = 4;
}

message LevelsPlaylistDef {
  // Specifies the changes to the scenario per level.
  string base_scenario = 1;

  // If unspecified defaults to 1.
  float min_level = 2;
  float max_level = 3;
  // The amount to increment for each playlist item. i.e. 0.5 -> 1, 1.5, 2, ..
  float level_step = 4;

  int32 num_plays_per_level = 5;
  
  // Override the target score of the base scenario.
  float target_score = 6;
}

message PlaylistItem {
  string scenario = 1;
  int32 num_plays = 2;
}
