edition = "2023";

import "common.proto";

package aim;

message HealthBarSettings {
  bool show = 1 [features.field_presence = IMPLICIT];
  bool only_damaged = 2 [features.field_presence = IMPLICIT];
  float height = 3;
  float width = 4;
  float height_above_target = 5;
}

message Settings {
  float dpi = 1;
  float cm_per_360 = 2;
  string theme_name = 4;

  bool enable_metronome = 3 [features.field_presence = IMPLICIT];
  float metronome_bpm = 5;

  float crosshair_size = 6;
  string current_crosshair_name = 7;

  bool disable_click_to_start = 8 [features.field_presence = IMPLICIT];

  Keybinds keybinds = 9;

  // Left click is automatically held down in tracking scenarios.
  bool auto_hold_tracking = 10 [features.field_presence = IMPLICIT];

  HealthBarSettings health_bar = 12;

  bool disable_per_scenario_settings = 13 [features.field_presence = IMPLICIT];

  float max_render_fps = 14;

  // Vsync, immediate, mailbox
  PresentMode present_mode = 15;

  SoundSettings sounds = 16;

  // Time in seconds for a start countdown at the beginning of scenarios.
  float start_countdown_time = 17;
}

message SoundItem {
    string name = 1;
    // Optional. Specific volume level for the sound.
    float volume_level = 2;
}

message SoundSettings {
  // Percent value from 0 to 1.
  float master_volume_level = 1;

  SoundItem hit = 10;
  SoundItem kill = 11;
  SoundItem metronome = 12;
  SoundItem shoot = 13;
  SoundItem reload = 14;
}

message ScenarioSettings {
  float cm_per_360 = 1;
  float cm_per_360_jitter = 6;
  string theme_name = 2;
  float metronome_bpm = 3;
  float crosshair_size = 4;
  string crosshair_name = 5;
  bool auto_hold_tracking = 7 [features.field_presence = IMPLICIT];
  HealthBarSettings health_bar = 8;
  bool enable_metronome = 9 [features.field_presence = IMPLICIT];
}

message KeyMapping {
  string mapping1 = 1;
  string mapping2 = 2;
  string mapping3 = 3;
  string mapping4 = 4;
}

message Keybinds {
  KeyMapping fire = 1;
  KeyMapping restart_scenario = 2;
  KeyMapping next_scenario = 3;
  KeyMapping quick_settings = 4;
  KeyMapping adjust_crosshair_size = 5;
  KeyMapping quick_metronome = 6;
  KeyMapping edit_scenario = 7;
}
