// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundle.proto
// Protobuf C++ Version: 5.29.3

#include "bundle.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aim {

inline constexpr BundlePlaylist::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        def_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR BundlePlaylist::BundlePlaylist(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BundlePlaylistDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BundlePlaylistDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BundlePlaylistDefaultTypeInternal() {}
  union {
    BundlePlaylist _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BundlePlaylistDefaultTypeInternal _BundlePlaylist_default_instance_;

inline constexpr BundleScenario::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        def_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR BundleScenario::BundleScenario(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BundleScenarioDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BundleScenarioDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BundleScenarioDefaultTypeInternal() {}
  union {
    BundleScenario _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BundleScenarioDefaultTypeInternal _BundleScenario_default_instance_;

inline constexpr BundleFile::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : scenarios_{},
        playlists_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BundleFile::BundleFile(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BundleFileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BundleFileDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BundleFileDefaultTypeInternal() {}
  union {
    BundleFile _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BundleFileDefaultTypeInternal _BundleFile_default_instance_;
}  // namespace aim
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_bundle_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_bundle_2eproto = nullptr;
const ::uint32_t
    TableStruct_bundle_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::aim::BundleScenario, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::aim::BundleScenario, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::aim::BundleScenario, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::aim::BundleScenario, _impl_.def_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::aim::BundlePlaylist, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::aim::BundlePlaylist, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::aim::BundlePlaylist, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::aim::BundlePlaylist, _impl_.def_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::aim::BundleFile, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::aim::BundleFile, _impl_.scenarios_),
        PROTOBUF_FIELD_OFFSET(::aim::BundleFile, _impl_.playlists_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::aim::BundleScenario)},
        {12, 22, -1, sizeof(::aim::BundlePlaylist)},
        {24, -1, -1, sizeof(::aim::BundleFile)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::aim::_BundleScenario_default_instance_._instance,
    &::aim::_BundlePlaylist_default_instance_._instance,
    &::aim::_BundleFile_default_instance_._instance,
};
const char descriptor_table_protodef_bundle_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014bundle.proto\022\003aim\032\016scenario.proto\032\016pla"
    "ylist.proto\"=\n\016BundleScenario\022\014\n\004name\030\001 "
    "\001(\t\022\035\n\003def\030\002 \001(\0132\020.aim.ScenarioDef\"=\n\016Bu"
    "ndlePlaylist\022\014\n\004name\030\001 \001(\t\022\035\n\003def\030\002 \001(\0132"
    "\020.aim.PlaylistDef\"\\\n\nBundleFile\022&\n\tscena"
    "rios\030\001 \003(\0132\023.aim.BundleScenario\022&\n\tplayl"
    "ists\030\002 \003(\0132\023.aim.BundlePlaylistb\010edition"
    "sp\350\007"
};
static const ::_pbi::DescriptorTable* const descriptor_table_bundle_2eproto_deps[2] =
    {
        &::descriptor_table_playlist_2eproto,
        &::descriptor_table_scenario_2eproto,
};
static ::absl::once_flag descriptor_table_bundle_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_bundle_2eproto = {
    false,
    false,
    284,
    descriptor_table_protodef_bundle_2eproto,
    "bundle.proto",
    &descriptor_table_bundle_2eproto_once,
    descriptor_table_bundle_2eproto_deps,
    2,
    3,
    schemas,
    file_default_instances,
    TableStruct_bundle_2eproto::offsets,
    file_level_enum_descriptors_bundle_2eproto,
    file_level_service_descriptors_bundle_2eproto,
};
namespace aim {
// ===================================================================

class BundleScenario::_Internal {
 public:
  using HasBits =
      decltype(std::declval<BundleScenario>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_._has_bits_);
};

void BundleScenario::clear_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.def_ != nullptr) _impl_.def_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
BundleScenario::BundleScenario(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.BundleScenario)
}
inline PROTOBUF_NDEBUG_INLINE BundleScenario::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::aim::BundleScenario& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

BundleScenario::BundleScenario(
    ::google::protobuf::Arena* arena,
    const BundleScenario& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BundleScenario* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.def_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::aim::ScenarioDef>(
                              arena, *from._impl_.def_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:aim.BundleScenario)
}
inline PROTOBUF_NDEBUG_INLINE BundleScenario::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena) {}

inline void BundleScenario::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.def_ = {};
}
BundleScenario::~BundleScenario() {
  // @@protoc_insertion_point(destructor:aim.BundleScenario)
  SharedDtor(*this);
}
inline void BundleScenario::SharedDtor(MessageLite& self) {
  BundleScenario& this_ = static_cast<BundleScenario&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.def_;
  this_._impl_.~Impl_();
}

inline void* BundleScenario::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BundleScenario(arena);
}
constexpr auto BundleScenario::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(BundleScenario),
                                            alignof(BundleScenario));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BundleScenario::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BundleScenario_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BundleScenario::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BundleScenario>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BundleScenario::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BundleScenario>(), &BundleScenario::ByteSizeLong,
            &BundleScenario::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_._cached_size_),
        false,
    },
    &BundleScenario::kDescriptorMethods,
    &descriptor_table_bundle_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BundleScenario::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 31, 2> BundleScenario::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::BundleScenario>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .aim.ScenarioDef def = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_.def_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .aim.ScenarioDef def = 2;
    {PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_.def_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::aim::ScenarioDef>()},
  }}, {{
    "\22\4\0\0\0\0\0\0"
    "aim.BundleScenario"
    "name"
  }},
};

PROTOBUF_NOINLINE void BundleScenario::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.BundleScenario)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.def_ != nullptr);
      _impl_.def_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BundleScenario::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BundleScenario& this_ = static_cast<const BundleScenario&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BundleScenario::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BundleScenario& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:aim.BundleScenario)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // string name = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aim.BundleScenario.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // .aim.ScenarioDef def = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.def_, this_._impl_.def_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:aim.BundleScenario)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BundleScenario::ByteSizeLong(const MessageLite& base) {
          const BundleScenario& this_ = static_cast<const BundleScenario&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BundleScenario::ByteSizeLong() const {
          const BundleScenario& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:aim.BundleScenario)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // string name = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // .aim.ScenarioDef def = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.def_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BundleScenario::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BundleScenario*>(&to_msg);
  auto& from = static_cast<const BundleScenario&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.BundleScenario)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.def_ != nullptr);
      if (_this->_impl_.def_ == nullptr) {
        _this->_impl_.def_ =
            ::google::protobuf::Message::CopyConstruct<::aim::ScenarioDef>(arena, *from._impl_.def_);
      } else {
        _this->_impl_.def_->MergeFrom(*from._impl_.def_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BundleScenario::CopyFrom(const BundleScenario& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aim.BundleScenario)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BundleScenario::InternalSwap(BundleScenario* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  swap(_impl_.def_, other->_impl_.def_);
}

::google::protobuf::Metadata BundleScenario::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BundlePlaylist::_Internal {
 public:
  using HasBits =
      decltype(std::declval<BundlePlaylist>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_._has_bits_);
};

void BundlePlaylist::clear_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.def_ != nullptr) _impl_.def_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
BundlePlaylist::BundlePlaylist(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.BundlePlaylist)
}
inline PROTOBUF_NDEBUG_INLINE BundlePlaylist::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::aim::BundlePlaylist& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

BundlePlaylist::BundlePlaylist(
    ::google::protobuf::Arena* arena,
    const BundlePlaylist& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BundlePlaylist* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.def_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::aim::PlaylistDef>(
                              arena, *from._impl_.def_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:aim.BundlePlaylist)
}
inline PROTOBUF_NDEBUG_INLINE BundlePlaylist::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena) {}

inline void BundlePlaylist::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.def_ = {};
}
BundlePlaylist::~BundlePlaylist() {
  // @@protoc_insertion_point(destructor:aim.BundlePlaylist)
  SharedDtor(*this);
}
inline void BundlePlaylist::SharedDtor(MessageLite& self) {
  BundlePlaylist& this_ = static_cast<BundlePlaylist&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.def_;
  this_._impl_.~Impl_();
}

inline void* BundlePlaylist::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BundlePlaylist(arena);
}
constexpr auto BundlePlaylist::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(BundlePlaylist),
                                            alignof(BundlePlaylist));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BundlePlaylist::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BundlePlaylist_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BundlePlaylist::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BundlePlaylist>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BundlePlaylist::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BundlePlaylist>(), &BundlePlaylist::ByteSizeLong,
            &BundlePlaylist::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_._cached_size_),
        false,
    },
    &BundlePlaylist::kDescriptorMethods,
    &descriptor_table_bundle_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BundlePlaylist::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 31, 2> BundlePlaylist::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::BundlePlaylist>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .aim.PlaylistDef def = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_.def_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .aim.PlaylistDef def = 2;
    {PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_.def_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::aim::PlaylistDef>()},
  }}, {{
    "\22\4\0\0\0\0\0\0"
    "aim.BundlePlaylist"
    "name"
  }},
};

PROTOBUF_NOINLINE void BundlePlaylist::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.BundlePlaylist)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.def_ != nullptr);
      _impl_.def_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BundlePlaylist::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BundlePlaylist& this_ = static_cast<const BundlePlaylist&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BundlePlaylist::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BundlePlaylist& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:aim.BundlePlaylist)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // string name = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aim.BundlePlaylist.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // .aim.PlaylistDef def = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.def_, this_._impl_.def_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:aim.BundlePlaylist)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BundlePlaylist::ByteSizeLong(const MessageLite& base) {
          const BundlePlaylist& this_ = static_cast<const BundlePlaylist&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BundlePlaylist::ByteSizeLong() const {
          const BundlePlaylist& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:aim.BundlePlaylist)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // string name = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // .aim.PlaylistDef def = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.def_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BundlePlaylist::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BundlePlaylist*>(&to_msg);
  auto& from = static_cast<const BundlePlaylist&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.BundlePlaylist)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.def_ != nullptr);
      if (_this->_impl_.def_ == nullptr) {
        _this->_impl_.def_ =
            ::google::protobuf::Message::CopyConstruct<::aim::PlaylistDef>(arena, *from._impl_.def_);
      } else {
        _this->_impl_.def_->MergeFrom(*from._impl_.def_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BundlePlaylist::CopyFrom(const BundlePlaylist& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aim.BundlePlaylist)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BundlePlaylist::InternalSwap(BundlePlaylist* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  swap(_impl_.def_, other->_impl_.def_);
}

::google::protobuf::Metadata BundlePlaylist::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BundleFile::_Internal {
 public:
};

BundleFile::BundleFile(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.BundleFile)
}
inline PROTOBUF_NDEBUG_INLINE BundleFile::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::aim::BundleFile& from_msg)
      : scenarios_{visibility, arena, from.scenarios_},
        playlists_{visibility, arena, from.playlists_},
        _cached_size_{0} {}

BundleFile::BundleFile(
    ::google::protobuf::Arena* arena,
    const BundleFile& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BundleFile* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:aim.BundleFile)
}
inline PROTOBUF_NDEBUG_INLINE BundleFile::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : scenarios_{visibility, arena},
        playlists_{visibility, arena},
        _cached_size_{0} {}

inline void BundleFile::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BundleFile::~BundleFile() {
  // @@protoc_insertion_point(destructor:aim.BundleFile)
  SharedDtor(*this);
}
inline void BundleFile::SharedDtor(MessageLite& self) {
  BundleFile& this_ = static_cast<BundleFile&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* BundleFile::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BundleFile(arena);
}
constexpr auto BundleFile::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.scenarios_) +
          decltype(BundleFile::_impl_.scenarios_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.playlists_) +
          decltype(BundleFile::_impl_.playlists_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(BundleFile), alignof(BundleFile), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BundleFile::PlacementNew_,
                                 sizeof(BundleFile),
                                 alignof(BundleFile));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BundleFile::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BundleFile_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BundleFile::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BundleFile>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BundleFile::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BundleFile>(), &BundleFile::ByteSizeLong,
            &BundleFile::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BundleFile, _impl_._cached_size_),
        false,
    },
    &BundleFile::kDescriptorMethods,
    &descriptor_table_bundle_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BundleFile::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> BundleFile::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::BundleFile>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .aim.BundlePlaylist playlists = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.playlists_)}},
    // repeated .aim.BundleScenario scenarios = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.scenarios_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .aim.BundleScenario scenarios = 1;
    {PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.scenarios_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .aim.BundlePlaylist playlists = 2;
    {PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.playlists_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::aim::BundleScenario>()},
    {::_pbi::TcParser::GetTable<::aim::BundlePlaylist>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void BundleFile::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.BundleFile)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.scenarios_.Clear();
  _impl_.playlists_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BundleFile::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BundleFile& this_ = static_cast<const BundleFile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BundleFile::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BundleFile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:aim.BundleFile)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .aim.BundleScenario scenarios = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_scenarios_size());
               i < n; i++) {
            const auto& repfield = this_._internal_scenarios().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .aim.BundlePlaylist playlists = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_playlists_size());
               i < n; i++) {
            const auto& repfield = this_._internal_playlists().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:aim.BundleFile)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BundleFile::ByteSizeLong(const MessageLite& base) {
          const BundleFile& this_ = static_cast<const BundleFile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BundleFile::ByteSizeLong() const {
          const BundleFile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:aim.BundleFile)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .aim.BundleScenario scenarios = 1;
            {
              total_size += 1UL * this_._internal_scenarios_size();
              for (const auto& msg : this_._internal_scenarios()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .aim.BundlePlaylist playlists = 2;
            {
              total_size += 1UL * this_._internal_playlists_size();
              for (const auto& msg : this_._internal_playlists()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BundleFile::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BundleFile*>(&to_msg);
  auto& from = static_cast<const BundleFile&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.BundleFile)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_scenarios()->MergeFrom(
      from._internal_scenarios());
  _this->_internal_mutable_playlists()->MergeFrom(
      from._internal_playlists());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BundleFile::CopyFrom(const BundleFile& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aim.BundleFile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BundleFile::InternalSwap(BundleFile* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.scenarios_.InternalSwap(&other->_impl_.scenarios_);
  _impl_.playlists_.InternalSwap(&other->_impl_.playlists_);
}

::google::protobuf::Metadata BundleFile::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace aim
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_bundle_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
