// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: guide.proto
// Protobuf C++ Version: 6.33.5

#ifndef guide_2eproto_2epb_2eh
#define guide_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_guide_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_guide_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_guide_2eproto;
}  // extern "C"
namespace aim {
class GuideDef;
struct GuideDefDefaultTypeInternal;
extern GuideDefDefaultTypeInternal _GuideDef_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GuideDef_class_data_;
class GuideSection;
struct GuideSectionDefaultTypeInternal;
extern GuideSectionDefaultTypeInternal _GuideSection_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GuideSection_class_data_;
}  // namespace aim
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace aim {

// ===================================================================


// -------------------------------------------------------------------

class GuideSection final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aim.GuideSection) */ {
 public:
  inline GuideSection() : GuideSection(nullptr) {}
  ~GuideSection() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GuideSection* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GuideSection));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GuideSection(::google::protobuf::internal::ConstantInitialized);

  inline GuideSection(const GuideSection& from) : GuideSection(nullptr, from) {}
  inline GuideSection(GuideSection&& from) noexcept
      : GuideSection(nullptr, ::std::move(from)) {}
  inline GuideSection& operator=(const GuideSection& from) {
    CopyFrom(from);
    return *this;
  }
  inline GuideSection& operator=(GuideSection&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GuideSection& default_instance() {
    return *reinterpret_cast<const GuideSection*>(
        &_GuideSection_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GuideSection& a, GuideSection& b) { a.Swap(&b); }
  inline void Swap(GuideSection* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GuideSection* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GuideSection* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GuideSection>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GuideSection& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GuideSection& from) { GuideSection::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GuideSection* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aim.GuideSection"; }

  explicit GuideSection(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GuideSection(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GuideSection& from);
  GuideSection(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GuideSection&& from) noexcept
      : GuideSection(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlaylistsFieldNumber = 2,
    kGuidesFieldNumber = 3,
    kTextFieldNumber = 1,
  };
  // repeated string playlists = 2;
  int playlists_size() const;
  private:
  int _internal_playlists_size() const;

  public:
  void clear_playlists() ;
  const ::std::string& playlists(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_playlists(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_playlists(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_playlists();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_playlists(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& playlists() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_playlists();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_playlists() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_playlists();

  public:
  // repeated string guides = 3;
  int guides_size() const;
  private:
  int _internal_guides_size() const;

  public:
  void clear_guides() ;
  const ::std::string& guides(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_guides(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_guides(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_guides();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_guides(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& guides() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_guides();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_guides() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_guides();

  public:
  // string text = 1;
  bool has_text() const;
  void clear_text() ;
  const ::std::string& text() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_text(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_text();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_text();
  void set_allocated_text(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_text() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_text(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_text();

  public:
  // @@protoc_insertion_point(class_scope:aim.GuideSection)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 44,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GuideSection& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> playlists_;
    ::google::protobuf::RepeatedPtrField<::std::string> guides_;
    ::google::protobuf::internal::ArenaStringPtr text_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_guide_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GuideSection_class_data_;
// -------------------------------------------------------------------

class GuideDef final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aim.GuideDef) */ {
 public:
  inline GuideDef() : GuideDef(nullptr) {}
  ~GuideDef() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GuideDef* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GuideDef));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GuideDef(::google::protobuf::internal::ConstantInitialized);

  inline GuideDef(const GuideDef& from) : GuideDef(nullptr, from) {}
  inline GuideDef(GuideDef&& from) noexcept
      : GuideDef(nullptr, ::std::move(from)) {}
  inline GuideDef& operator=(const GuideDef& from) {
    CopyFrom(from);
    return *this;
  }
  inline GuideDef& operator=(GuideDef&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GuideDef& default_instance() {
    return *reinterpret_cast<const GuideDef*>(
        &_GuideDef_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GuideDef& a, GuideDef& b) { a.Swap(&b); }
  inline void Swap(GuideDef* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GuideDef* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GuideDef* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GuideDef>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GuideDef& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GuideDef& from) { GuideDef::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GuideDef* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aim.GuideDef"; }

  explicit GuideDef(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GuideDef(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GuideDef& from);
  GuideDef(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GuideDef&& from) noexcept
      : GuideDef(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSectionsFieldNumber = 1,
  };
  // repeated .aim.GuideSection sections = 1;
  int sections_size() const;
  private:
  int _internal_sections_size() const;

  public:
  void clear_sections() ;
  ::aim::GuideSection* PROTOBUF_NONNULL mutable_sections(int index);
  ::google::protobuf::RepeatedPtrField<::aim::GuideSection>* PROTOBUF_NONNULL mutable_sections();

  private:
  const ::google::protobuf::RepeatedPtrField<::aim::GuideSection>& _internal_sections() const;
  ::google::protobuf::RepeatedPtrField<::aim::GuideSection>* PROTOBUF_NONNULL _internal_mutable_sections();
  public:
  const ::aim::GuideSection& sections(int index) const;
  ::aim::GuideSection* PROTOBUF_NONNULL add_sections();
  const ::google::protobuf::RepeatedPtrField<::aim::GuideSection>& sections() const;
  // @@protoc_insertion_point(class_scope:aim.GuideDef)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GuideDef& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::aim::GuideSection > sections_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_guide_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GuideDef_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GuideSection

// string text = 1;
inline bool GuideSection::has_text() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void GuideSection::clear_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& GuideSection::text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.GuideSection.text)
  return _internal_text();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void GuideSection::set_text(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aim.GuideSection.text)
}
inline ::std::string* PROTOBUF_NONNULL GuideSection::mutable_text()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:aim.GuideSection.text)
  return _s;
}
inline const ::std::string& GuideSection::_internal_text() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.text_.Get();
}
inline void GuideSection::_internal_set_text(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL GuideSection::_internal_mutable_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.text_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE GuideSection::release_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aim.GuideSection.text)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.text_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.text_.Set("", GetArena());
  }
  return released;
}
inline void GuideSection::set_allocated_text(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.text_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aim.GuideSection.text)
}

// repeated string playlists = 2;
inline int GuideSection::_internal_playlists_size() const {
  return _internal_playlists().size();
}
inline int GuideSection::playlists_size() const {
  return _internal_playlists_size();
}
inline void GuideSection::clear_playlists() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playlists_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL GuideSection::add_playlists()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_playlists()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:aim.GuideSection.playlists)
  return _s;
}
inline const ::std::string& GuideSection::playlists(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.GuideSection.playlists)
  return _internal_playlists().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL GuideSection::mutable_playlists(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:aim.GuideSection.playlists)
  return _internal_mutable_playlists()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void GuideSection::set_playlists(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_playlists()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:aim.GuideSection.playlists)
}
template <typename Arg_, typename... Args_>
inline void GuideSection::add_playlists(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_playlists(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:aim.GuideSection.playlists)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& GuideSection::playlists()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:aim.GuideSection.playlists)
  return _internal_playlists();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
GuideSection::mutable_playlists() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:aim.GuideSection.playlists)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_playlists();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
GuideSection::_internal_playlists() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.playlists_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
GuideSection::_internal_mutable_playlists() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.playlists_;
}

// repeated string guides = 3;
inline int GuideSection::_internal_guides_size() const {
  return _internal_guides().size();
}
inline int GuideSection::guides_size() const {
  return _internal_guides_size();
}
inline void GuideSection::clear_guides() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.guides_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::std::string* PROTOBUF_NONNULL GuideSection::add_guides()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_guides()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add_mutable:aim.GuideSection.guides)
  return _s;
}
inline const ::std::string& GuideSection::guides(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.GuideSection.guides)
  return _internal_guides().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL GuideSection::mutable_guides(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:aim.GuideSection.guides)
  return _internal_mutable_guides()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void GuideSection::set_guides(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_guides()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:aim.GuideSection.guides)
}
template <typename Arg_, typename... Args_>
inline void GuideSection::add_guides(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_guides(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:aim.GuideSection.guides)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& GuideSection::guides()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:aim.GuideSection.guides)
  return _internal_guides();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
GuideSection::mutable_guides() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:aim.GuideSection.guides)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_guides();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
GuideSection::_internal_guides() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.guides_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
GuideSection::_internal_mutable_guides() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.guides_;
}

// -------------------------------------------------------------------

// GuideDef

// repeated .aim.GuideSection sections = 1;
inline int GuideDef::_internal_sections_size() const {
  return _internal_sections().size();
}
inline int GuideDef::sections_size() const {
  return _internal_sections_size();
}
inline void GuideDef::clear_sections() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sections_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::aim::GuideSection* PROTOBUF_NONNULL GuideDef::mutable_sections(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:aim.GuideDef.sections)
  return _internal_mutable_sections()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::aim::GuideSection>* PROTOBUF_NONNULL GuideDef::mutable_sections()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:aim.GuideDef.sections)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_sections();
}
inline const ::aim::GuideSection& GuideDef::sections(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.GuideDef.sections)
  return _internal_sections().Get(index);
}
inline ::aim::GuideSection* PROTOBUF_NONNULL GuideDef::add_sections()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::aim::GuideSection* _add =
      _internal_mutable_sections()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:aim.GuideDef.sections)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::aim::GuideSection>& GuideDef::sections() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:aim.GuideDef.sections)
  return _internal_sections();
}
inline const ::google::protobuf::RepeatedPtrField<::aim::GuideSection>&
GuideDef::_internal_sections() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sections_;
}
inline ::google::protobuf::RepeatedPtrField<::aim::GuideSection>* PROTOBUF_NONNULL
GuideDef::_internal_mutable_sections() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.sections_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace aim


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // guide_2eproto_2epb_2eh
