// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: playlist.proto
// Protobuf C++ Version: 6.33.5

#include "playlist.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aim {

inline constexpr PlaylistItem::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        scenario_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        num_plays_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PlaylistItem::PlaylistItem(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PlaylistItem_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlaylistItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlaylistItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlaylistItemDefaultTypeInternal() {}
  union {
    PlaylistItem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlaylistItemDefaultTypeInternal _PlaylistItem_default_instance_;

inline constexpr LevelsPlaylistDef::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        base_scenario_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        min_level_{0},
        max_level_{0},
        level_step_{0},
        num_plays_per_level_{0},
        target_score_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LevelsPlaylistDef::LevelsPlaylistDef(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(LevelsPlaylistDef_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LevelsPlaylistDefDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LevelsPlaylistDefDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LevelsPlaylistDefDefaultTypeInternal() {}
  union {
    LevelsPlaylistDef _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LevelsPlaylistDefDefaultTypeInternal _LevelsPlaylistDef_default_instance_;

inline constexpr PlaylistDef::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        items_{},
        description_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        levels_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR PlaylistDef::PlaylistDef(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PlaylistDef_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlaylistDefDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlaylistDefDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlaylistDefDefaultTypeInternal() {}
  union {
    PlaylistDef _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlaylistDefDefaultTypeInternal _PlaylistDef_default_instance_;
}  // namespace aim
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_playlist_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_playlist_2eproto = nullptr;
const ::uint32_t
    TableStruct_playlist_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aim::PlaylistDef, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aim::PlaylistDef, _impl_.description_),
        PROTOBUF_FIELD_OFFSET(::aim::PlaylistDef, _impl_.items_),
        PROTOBUF_FIELD_OFFSET(::aim::PlaylistDef, _impl_.levels_),
        1,
        0,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aim::LevelsPlaylistDef, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aim::LevelsPlaylistDef, _impl_.base_scenario_),
        PROTOBUF_FIELD_OFFSET(::aim::LevelsPlaylistDef, _impl_.min_level_),
        PROTOBUF_FIELD_OFFSET(::aim::LevelsPlaylistDef, _impl_.max_level_),
        PROTOBUF_FIELD_OFFSET(::aim::LevelsPlaylistDef, _impl_.level_step_),
        PROTOBUF_FIELD_OFFSET(::aim::LevelsPlaylistDef, _impl_.num_plays_per_level_),
        PROTOBUF_FIELD_OFFSET(::aim::LevelsPlaylistDef, _impl_.target_score_),
        0,
        1,
        2,
        3,
        4,
        5,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aim::PlaylistItem, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aim::PlaylistItem, _impl_.scenario_),
        PROTOBUF_FIELD_OFFSET(::aim::PlaylistItem, _impl_.num_plays_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aim::PlaylistDef)},
        {9, sizeof(::aim::LevelsPlaylistDef)},
        {24, sizeof(::aim::PlaylistItem)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aim::_PlaylistDef_default_instance_._instance,
    &::aim::_LevelsPlaylistDef_default_instance_._instance,
    &::aim::_PlaylistItem_default_instance_._instance,
};
const char descriptor_table_protodef_playlist_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016playlist.proto\022\003aim\"l\n\013PlaylistDef\022\023\n\013"
    "description\030\001 \001(\t\022 \n\005items\030\002 \003(\0132\021.aim.P"
    "laylistItem\022&\n\006levels\030\004 \001(\0132\026.aim.Levels"
    "PlaylistDef\"\227\001\n\021LevelsPlaylistDef\022\025\n\rbas"
    "e_scenario\030\001 \001(\t\022\021\n\tmin_level\030\002 \001(\002\022\021\n\tm"
    "ax_level\030\003 \001(\002\022\022\n\nlevel_step\030\004 \001(\002\022\033\n\023nu"
    "m_plays_per_level\030\005 \001(\005\022\024\n\014target_score\030"
    "\006 \001(\002\"3\n\014PlaylistItem\022\020\n\010scenario\030\001 \001(\t\022"
    "\021\n\tnum_plays\030\002 \001(\005b\010editionsp\350\007"
};
static ::absl::once_flag descriptor_table_playlist_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_playlist_2eproto = {
    false,
    false,
    351,
    descriptor_table_protodef_playlist_2eproto,
    "playlist.proto",
    &descriptor_table_playlist_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_playlist_2eproto::offsets,
    file_level_enum_descriptors_playlist_2eproto,
    file_level_service_descriptors_playlist_2eproto,
};
namespace aim {
// ===================================================================

class PlaylistDef::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PlaylistDef>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlaylistDef, _impl_._has_bits_);
};

PlaylistDef::PlaylistDef(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistDef_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.PlaylistDef)
}
PROTOBUF_NDEBUG_INLINE PlaylistDef::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aim::PlaylistDef& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        items_{visibility, arena, from.items_},
        description_(arena, from.description_) {}

PlaylistDef::PlaylistDef(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PlaylistDef& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistDef_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PlaylistDef* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.levels_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.levels_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:aim.PlaylistDef)
}
PROTOBUF_NDEBUG_INLINE PlaylistDef::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        items_{visibility, arena},
        description_(arena) {}

inline void PlaylistDef::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.levels_ = {};
}
PlaylistDef::~PlaylistDef() {
  // @@protoc_insertion_point(destructor:aim.PlaylistDef)
  SharedDtor(*this);
}
inline void PlaylistDef::SharedDtor(MessageLite& self) {
  PlaylistDef& this_ = static_cast<PlaylistDef&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.description_.Destroy();
  delete this_._impl_.levels_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PlaylistDef::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PlaylistDef(arena);
}
constexpr auto PlaylistDef::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PlaylistDef, _impl_.items_) +
          decltype(PlaylistDef::_impl_.items_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(PlaylistDef), alignof(PlaylistDef), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PlaylistDef::PlacementNew_,
                                 sizeof(PlaylistDef),
                                 alignof(PlaylistDef));
  }
}
constexpr auto PlaylistDef::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PlaylistDef_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PlaylistDef::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PlaylistDef>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PlaylistDef::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PlaylistDef>(), &PlaylistDef::ByteSizeLong,
              &PlaylistDef::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PlaylistDef, _impl_._cached_size_),
          false,
      },
      &PlaylistDef::kDescriptorMethods,
      &descriptor_table_playlist_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PlaylistDef_class_data_ =
        PlaylistDef::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PlaylistDef::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PlaylistDef_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PlaylistDef_class_data_.tc_table);
  return PlaylistDef_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 35, 2>
PlaylistDef::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlaylistDef, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967284,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PlaylistDef_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::PlaylistDef>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .aim.LevelsPlaylistDef levels = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 2, 1,
      PROTOBUF_FIELD_OFFSET(PlaylistDef, _impl_.levels_)}},
    // string description = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistDef, _impl_.description_)}},
    // repeated .aim.PlaylistItem items = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistDef, _impl_.items_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string description = 1;
    {PROTOBUF_FIELD_OFFSET(PlaylistDef, _impl_.description_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .aim.PlaylistItem items = 2;
    {PROTOBUF_FIELD_OFFSET(PlaylistDef, _impl_.items_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // .aim.LevelsPlaylistDef levels = 4;
    {PROTOBUF_FIELD_OFFSET(PlaylistDef, _impl_.levels_), _Internal::kHasBitsOffset + 2, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::aim::PlaylistItem>()},
      {::_pbi::TcParser::GetTable<::aim::LevelsPlaylistDef>()},
  }},
  {{
    "\17\13\0\0\0\0\0\0"
    "aim.PlaylistDef"
    "description"
  }},
};
PROTOBUF_NOINLINE void PlaylistDef::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.PlaylistDef)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.items_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.description_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.levels_ != nullptr);
      _impl_.levels_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PlaylistDef::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PlaylistDef& this_ = static_cast<const PlaylistDef&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PlaylistDef::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PlaylistDef& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aim.PlaylistDef)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string description = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_description();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aim.PlaylistDef.description");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated .aim.PlaylistItem items = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_items_size());
         i < n; i++) {
      const auto& repfield = this_._internal_items().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // .aim.LevelsPlaylistDef levels = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.levels_, this_._impl_.levels_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aim.PlaylistDef)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PlaylistDef::ByteSizeLong(const MessageLite& base) {
  const PlaylistDef& this_ = static_cast<const PlaylistDef&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PlaylistDef::ByteSizeLong() const {
  const PlaylistDef& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aim.PlaylistDef)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // repeated .aim.PlaylistItem items = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_items_size();
      for (const auto& msg : this_._internal_items()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // string description = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_description());
    }
    // .aim.LevelsPlaylistDef levels = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.levels_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PlaylistDef::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PlaylistDef*>(&to_msg);
  auto& from = static_cast<const PlaylistDef&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.PlaylistDef)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_items()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_items());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_description(from._internal_description());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.levels_ != nullptr);
      if (_this->_impl_.levels_ == nullptr) {
        _this->_impl_.levels_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.levels_);
      } else {
        _this->_impl_.levels_->MergeFrom(*from._impl_.levels_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PlaylistDef::CopyFrom(const PlaylistDef& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aim.PlaylistDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlaylistDef::InternalSwap(PlaylistDef* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.description_, &other->_impl_.description_, arena);
  swap(_impl_.levels_, other->_impl_.levels_);
}

::google::protobuf::Metadata PlaylistDef::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LevelsPlaylistDef::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<LevelsPlaylistDef>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_._has_bits_);
};

LevelsPlaylistDef::LevelsPlaylistDef(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LevelsPlaylistDef_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.LevelsPlaylistDef)
}
PROTOBUF_NDEBUG_INLINE LevelsPlaylistDef::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aim::LevelsPlaylistDef& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        base_scenario_(arena, from.base_scenario_) {}

LevelsPlaylistDef::LevelsPlaylistDef(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const LevelsPlaylistDef& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LevelsPlaylistDef_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LevelsPlaylistDef* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, min_level_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, min_level_),
           offsetof(Impl_, target_score_) -
               offsetof(Impl_, min_level_) +
               sizeof(Impl_::target_score_));

  // @@protoc_insertion_point(copy_constructor:aim.LevelsPlaylistDef)
}
PROTOBUF_NDEBUG_INLINE LevelsPlaylistDef::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        base_scenario_(arena) {}

inline void LevelsPlaylistDef::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, min_level_),
           0,
           offsetof(Impl_, target_score_) -
               offsetof(Impl_, min_level_) +
               sizeof(Impl_::target_score_));
}
LevelsPlaylistDef::~LevelsPlaylistDef() {
  // @@protoc_insertion_point(destructor:aim.LevelsPlaylistDef)
  SharedDtor(*this);
}
inline void LevelsPlaylistDef::SharedDtor(MessageLite& self) {
  LevelsPlaylistDef& this_ = static_cast<LevelsPlaylistDef&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.base_scenario_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL LevelsPlaylistDef::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) LevelsPlaylistDef(arena);
}
constexpr auto LevelsPlaylistDef::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(LevelsPlaylistDef),
                                            alignof(LevelsPlaylistDef));
}
constexpr auto LevelsPlaylistDef::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_LevelsPlaylistDef_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &LevelsPlaylistDef::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<LevelsPlaylistDef>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &LevelsPlaylistDef::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<LevelsPlaylistDef>(), &LevelsPlaylistDef::ByteSizeLong,
              &LevelsPlaylistDef::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_._cached_size_),
          false,
      },
      &LevelsPlaylistDef::kDescriptorMethods,
      &descriptor_table_playlist_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull LevelsPlaylistDef_class_data_ =
        LevelsPlaylistDef::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
LevelsPlaylistDef::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LevelsPlaylistDef_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(LevelsPlaylistDef_class_data_.tc_table);
  return LevelsPlaylistDef_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 43, 2>
LevelsPlaylistDef::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    LevelsPlaylistDef_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::LevelsPlaylistDef>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string base_scenario = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.base_scenario_)}},
    // float min_level = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0,
      PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.min_level_)}},
    // float max_level = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0,
      PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.max_level_)}},
    // float level_step = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0,
      PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.level_step_)}},
    // int32 num_plays_per_level = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LevelsPlaylistDef, _impl_.num_plays_per_level_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.num_plays_per_level_)}},
    // float target_score = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 5, 0,
      PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.target_score_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string base_scenario = 1;
    {PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.base_scenario_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float min_level = 2;
    {PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.min_level_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float max_level = 3;
    {PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.max_level_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float level_step = 4;
    {PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.level_step_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // int32 num_plays_per_level = 5;
    {PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.num_plays_per_level_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // float target_score = 6;
    {PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.target_score_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
    "\25\15\0\0\0\0\0\0"
    "aim.LevelsPlaylistDef"
    "base_scenario"
  }},
};
PROTOBUF_NOINLINE void LevelsPlaylistDef::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.LevelsPlaylistDef)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.base_scenario_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000003eU)) {
    ::memset(&_impl_.min_level_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.target_score_) -
        reinterpret_cast<char*>(&_impl_.min_level_)) + sizeof(_impl_.target_score_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL LevelsPlaylistDef::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const LevelsPlaylistDef& this_ = static_cast<const LevelsPlaylistDef&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL LevelsPlaylistDef::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const LevelsPlaylistDef& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aim.LevelsPlaylistDef)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string base_scenario = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_base_scenario();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aim.LevelsPlaylistDef.base_scenario");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // float min_level = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this_._internal_min_level(), target);
  }

  // float max_level = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this_._internal_max_level(), target);
  }

  // float level_step = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this_._internal_level_step(), target);
  }

  // int32 num_plays_per_level = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
            stream, this_._internal_num_plays_per_level(), target);
  }

  // float target_score = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        6, this_._internal_target_score(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aim.LevelsPlaylistDef)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t LevelsPlaylistDef::ByteSizeLong(const MessageLite& base) {
  const LevelsPlaylistDef& this_ = static_cast<const LevelsPlaylistDef&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t LevelsPlaylistDef::ByteSizeLong() const {
  const LevelsPlaylistDef& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aim.LevelsPlaylistDef)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x0000002eU & cached_has_bits) * 5;
  if (BatchCheckHasBit(cached_has_bits, 0x00000011U)) {
    // string base_scenario = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_base_scenario());
    }
    // int32 num_plays_per_level = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_num_plays_per_level());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void LevelsPlaylistDef::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<LevelsPlaylistDef*>(&to_msg);
  auto& from = static_cast<const LevelsPlaylistDef&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.LevelsPlaylistDef)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_base_scenario(from._internal_base_scenario());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.min_level_ = from._impl_.min_level_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.max_level_ = from._impl_.max_level_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.level_step_ = from._impl_.level_step_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.num_plays_per_level_ = from._impl_.num_plays_per_level_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.target_score_ = from._impl_.target_score_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void LevelsPlaylistDef::CopyFrom(const LevelsPlaylistDef& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aim.LevelsPlaylistDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LevelsPlaylistDef::InternalSwap(LevelsPlaylistDef* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.base_scenario_, &other->_impl_.base_scenario_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.target_score_)
      + sizeof(LevelsPlaylistDef::_impl_.target_score_)
      - PROTOBUF_FIELD_OFFSET(LevelsPlaylistDef, _impl_.min_level_)>(
          reinterpret_cast<char*>(&_impl_.min_level_),
          reinterpret_cast<char*>(&other->_impl_.min_level_));
}

::google::protobuf::Metadata LevelsPlaylistDef::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PlaylistItem::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PlaylistItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlaylistItem, _impl_._has_bits_);
};

PlaylistItem::PlaylistItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistItem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.PlaylistItem)
}
PROTOBUF_NDEBUG_INLINE PlaylistItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aim::PlaylistItem& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        scenario_(arena, from.scenario_) {}

PlaylistItem::PlaylistItem(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PlaylistItem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistItem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PlaylistItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.num_plays_ = from._impl_.num_plays_;

  // @@protoc_insertion_point(copy_constructor:aim.PlaylistItem)
}
PROTOBUF_NDEBUG_INLINE PlaylistItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        scenario_(arena) {}

inline void PlaylistItem::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.num_plays_ = {};
}
PlaylistItem::~PlaylistItem() {
  // @@protoc_insertion_point(destructor:aim.PlaylistItem)
  SharedDtor(*this);
}
inline void PlaylistItem::SharedDtor(MessageLite& self) {
  PlaylistItem& this_ = static_cast<PlaylistItem&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.scenario_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PlaylistItem::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PlaylistItem(arena);
}
constexpr auto PlaylistItem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PlaylistItem),
                                            alignof(PlaylistItem));
}
constexpr auto PlaylistItem::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PlaylistItem_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PlaylistItem::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PlaylistItem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PlaylistItem::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PlaylistItem>(), &PlaylistItem::ByteSizeLong,
              &PlaylistItem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PlaylistItem, _impl_._cached_size_),
          false,
      },
      &PlaylistItem::kDescriptorMethods,
      &descriptor_table_playlist_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PlaylistItem_class_data_ =
        PlaylistItem::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PlaylistItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PlaylistItem_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PlaylistItem_class_data_.tc_table);
  return PlaylistItem_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 33, 2>
PlaylistItem::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlaylistItem, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PlaylistItem_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::PlaylistItem>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 num_plays = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlaylistItem, _impl_.num_plays_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistItem, _impl_.num_plays_)}},
    // string scenario = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistItem, _impl_.scenario_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string scenario = 1;
    {PROTOBUF_FIELD_OFFSET(PlaylistItem, _impl_.scenario_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 num_plays = 2;
    {PROTOBUF_FIELD_OFFSET(PlaylistItem, _impl_.num_plays_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\20\10\0\0\0\0\0\0"
    "aim.PlaylistItem"
    "scenario"
  }},
};
PROTOBUF_NOINLINE void PlaylistItem::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.PlaylistItem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.scenario_.ClearNonDefaultToEmpty();
  }
  _impl_.num_plays_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PlaylistItem::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PlaylistItem& this_ = static_cast<const PlaylistItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PlaylistItem::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PlaylistItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aim.PlaylistItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string scenario = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_scenario();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aim.PlaylistItem.scenario");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 num_plays = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_num_plays(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aim.PlaylistItem)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PlaylistItem::ByteSizeLong(const MessageLite& base) {
  const PlaylistItem& this_ = static_cast<const PlaylistItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PlaylistItem::ByteSizeLong() const {
  const PlaylistItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aim.PlaylistItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string scenario = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_scenario());
    }
    // int32 num_plays = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_num_plays());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PlaylistItem::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PlaylistItem*>(&to_msg);
  auto& from = static_cast<const PlaylistItem&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.PlaylistItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_scenario(from._internal_scenario());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.num_plays_ = from._impl_.num_plays_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PlaylistItem::CopyFrom(const PlaylistItem& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aim.PlaylistItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlaylistItem::InternalSwap(PlaylistItem* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.scenario_, &other->_impl_.scenario_, arena);
  swap(_impl_.num_plays_, other->_impl_.num_plays_);
}

::google::protobuf::Metadata PlaylistItem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace aim
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_playlist_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
